const router = require("express").Router();
let User = require("../models/user.model");

// Route: /users/add
// Creates a new user.
router.route("/add").post((res, req) => {
  // Only add user to database if it doesn't exist yet.
  User.find({ email: req.body.email })
    .catch(err => {
      const userData = { email: req.body.email };
      if (req.body.hasOwnProperty("name")) {
        userData["name"] = req.body.name;
      }
      const newUser = new User(userData);
      
      newUser.save()
        .then(() => res.json("You are saved to our database!"))
        .catch(err => res.status(400).json("Error: " + err));
    });
});

// Route: /users/
// Reads and returns all users from the MongoDB Atlas database.
router.route("/").get((req, res) => {
  User.find()
    .then(users => res.json(users))
    .catch(err => res.status(400).json("Error: " + err));
});

// Route: /users/:id
// Reads and returns a user with the specified object id, which is automatically generated by MongoDB.
router.route("/:id").get((req, res) => {
  User.findById(req.params.id)
    .then(user => res.json(user))
    .catch(err => res.status(400).json("Error: " + err));
});

module.exports = router;